import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import projectsRouter from "./projects";
import workspacesRouter from "./workspaces";
import filesRouter from "./files";
import runsRouter from "./runs";
import aiRouter from "./ai";
import adminRouter from "./admin";
import githubRouter from "./github";
import previewRouter from "./preview";
import secretsRouter from "./secrets";
import mobileRouter from "./mobile";
import domainsRouter from "./domains";
import apiKeysRouter from "./apiKeys";
import mcpRouter from "./mcp";
import mcpServerRouter from "./mcpServer";
import aiModelsRouter from "./aiModels";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/projects", projectsRouter);
router.use("/workspaces", workspacesRouter);
router.use("/files", filesRouter);
router.use("/runs", runsRouter);
router.use("/ai", aiRouter);
router.use("/ai", aiModelsRouter);
router.use("/admin", adminRouter);
router.use("/github", githubRouter);
router.use("/preview", previewRouter);
router.use("/projects", secretsRouter);
router.use("/mobile", mobileRouter);
router.use("/projects", domainsRouter);
router.use("/user/api-keys", apiKeysRouter);
router.use("/projects", mcpRouter);
router.use("/mcp", mcpServerRouter);

export default router;
